# Generated by Django 2.2.1 on 2019-05-25 15:45

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0002_auto_20190518_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInsertDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forkilla.Restaurant')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='ViewedRestaurants',
            fields=[
                ('id_vr', models.AutoField(primary_key=True, serialize=False)),
                ('restaurant', models.ManyToManyField(through='forkilla.RestaurantInsertDate', to='forkilla.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='restaurantinsertdate',
            name='viewedrestaurants',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forkilla.ViewedRestaurants'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time_slot', models.CharField(choices=[('morning_first', '12h00'), ('morning_second', '13h00'), ('morning_third', '14h00'), ('morning_fourth', '15h00'), ('evening_first', '20h00'), ('evening_second', '21h00'), ('evening_third', '22h00')], max_length=15)),
                ('num_people', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forkilla.Restaurant')),
            ],
        ),
    ]
