# Generated by Django 2.2.1 on 2019-05-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0003_auto_20190525_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Rice', 'Rice'), ('Fusi', 'Fusion'), ('BBQ', 'Barbecue'), ('Chin', 'Chinese'), ('Medi', 'Mediterranean'), ('Crep', 'Creperie'), ('Hind', 'Hindu'), ('Japa', 'Japanese'), ('Ital', 'Italian'), ('Mexi', 'Mexican'), ('Peru', 'Peruvian'), ('Russ', 'Russian'), ('Turk', 'Turkish'), ('Basq', 'Basque'), ('Vegy', 'Vegetarian'), ('Afri', 'African'), ('Egyp', 'Egyptian'), ('Grek', 'Greek')], max_length=5)),
                ('city', models.CharField(choices=[('barcelona', 'Barcelona'), ('madrid', 'Madrid'), ('paris', 'Paris'), ('chicago', 'Chicago'), ('ny', 'New York City'), ('toronto', 'Toronto'), ('london', 'London')], max_length=10)),
            ],
        ),
    ]
