# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-29 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0005_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='featured_photo',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
