# Generated by Django 2.2.1 on 2019-06-05 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0011_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
