# Generated by Django 2.2.1 on 2019-06-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forkilla', '0012_delete_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparatorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('price_average', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='pick',
            name='category',
            field=models.CharField(choices=[('Anyt', 'Anything'), ('Rice', 'Rice'), ('Fusi', 'Fusion'), ('BBQ', 'Barbecue'), ('Chin', 'Chinese'), ('Medi', 'Mediterranean'), ('Crep', 'Creperie'), ('Hind', 'Hindu'), ('Japa', 'Japanese'), ('Ital', 'Italian'), ('Mexi', 'Mexican'), ('Peru', 'Peruvian'), ('Russ', 'Russian'), ('Turk', 'Turkish'), ('Basq', 'Basque'), ('Vegy', 'Vegetarian'), ('Afri', 'African'), ('Egyp', 'Egyptian'), ('Grek', 'Greek')], max_length=5),
        ),
    ]
